eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user-auth
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/

application:
  mailing:
    frontend:
      activation-url: http://localhost:8081/activate-account
      reset-password-url: http://localhost:8081/reset-password

